[package]
name = "image-extras"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

include = ["src", "tests/reference.rs"]

[features]
default = ["pcx", "xbm"]
pcx = []
xbm = []

[dependencies]
image = {  git = "https://github.com/mstoeckl/image", branch = "xbm-hook", default-features = false }
pcx = "0.2.4"

[dev-dependencies]
image = {  git = "https://github.com/mstoeckl/image", branch = "xbm-hook", default-features = false, features = ["png"] }
walkdir = "2.5.0"

